### PR TITLE
Error message for Anvil execute and Error handling for the TRPC server

### LINKED ISSUE #125: Anvil execute error message
### Summary:

An error message should be displayed when creating an execution fails on the anvil side

### Expected behavior:

The error message created by anvil is forwarded and displayed to the user on anvil

### Actual behavior:

A generic error message appears

### Steps to reproduce:

1. Spoof anvil to throw an error on execution
2. Drop a pipeline and run it
3. Witness the error message displayed

### Zetaforge version:

main

### Operating System

Windows

### Other operating system:

_No response_

### Logs:

```bash
Not recorded
```

### Recording:

_No response_

### Anything else?:

_No response_

### PR DESCRIPTION
**Pull request by FGRCL**
Closes #125

### CODE REVIEW

File: frontend/src/components/ui/RunPipelineButton.jsx [hunk 1]
```diff
@@ -125,8 +125,7 @@ export default function RunPipelineButton({ children, action }) {
       });
       return newExecution; 
     } catch (error) {
-      console.error(`Pipeline execution failed: ${error}`)
-      setValidationErrorMsg(["Pipeline execution failed"])
+      setValidationErrorMsg([error.message])
```
Comment (jmagoon) [inline frontend/src/components/ui/RunPipelineButton.jsx:128]: null chain

**Review by jmagoon — APPROVED** [review]
